import type { MergePlan } from "./merge-remediation-plan";

// Kori Legacy Data Remediation v0 — Merge Executor v0's explicit resolution
// layer. Separated from MergePlan (an objective, always-true description of
// what the data looks like) and from the real executor (apply-lead-merge.ts)
// on purpose: a plan must never silently change what it reports just
// because someone wants a different outcome, and a resolution must never be
// inferred — every field here is something a human reviewed and stated
// explicitly for exactly one pair, never guessed or defaulted.

/**
 * The only supported override in v0: a human has reviewed a
 * COMMERCIAL_PROFILE_COLLISION on a specific (businessId, survivorLeadId,
 * loserLeadId) triple and decided the survivor's profile is the one to
 * keep — the loser's is discarded, never blended in (no field-level merge
 * exists yet; see server/db/scripts/merge-remediation-plan.ts's own doc
 * comment on why a collision is never silently resolved by default).
 */
export interface ApprovedCommercialProfileCollisionResolution {
  businessId: string;
  survivorLeadId: string;
  loserLeadId: string;
  resolution: "KEEP_SURVIVOR";
  approvedReason: string;
  /** ISO timestamp of the human review — caller-supplied, never generated by this module (this code has no clock of its own for approvals). */
  approvedAt: string;
}

/**
 * Scoped to exactly one pair. Passing this alongside a merge for a
 * DIFFERENT pair does nothing — applyLeadMerge only honors a resolution
 * whose businessId/survivorLeadId/loserLeadId match the merge actually
 * being attempted. Every other duplicate group's collision still blocks
 * automatically; constructing one of these correctly IS the human-review
 * step, and nothing in this codebase creates one on its own.
 */
export interface ApprovedMergeResolution {
  businessId: string;
  survivorLeadId: string;
  loserLeadId: string;
  commercialProfileCollision?: ApprovedCommercialProfileCollisionResolution;
}

function resolutionScopeMatches(resolution: ApprovedMergeResolution, businessId: string, survivorLeadId: string, loserLeadId: string): boolean {
  return resolution.businessId === businessId && resolution.survivorLeadId === survivorLeadId && resolution.loserLeadId === loserLeadId;
}

/**
 * True when `plan` has no commercial-profile collision at all (nothing to
 * resolve), OR when it does and `resolution` explicitly and exactly covers
 * this pair with `resolution: "KEEP_SURVIVOR"`. False otherwise — including
 * when `resolution` is present but scoped to a different pair, which must
 * never accidentally unblock an unrelated collision.
 */
export function commercialProfileCollisionIsResolved(plan: Pick<MergePlan, "businessId" | "survivorLeadId" | "loserLeadId" | "operations">, resolution?: ApprovedMergeResolution): boolean {
  if (plan.operations.commercialProfile.action !== "MANUAL_REVIEW_COLLISION") return true;
  if (!resolution?.commercialProfileCollision) return false;
  const r = resolution.commercialProfileCollision;
  if (r.resolution !== "KEEP_SURVIVOR") return false;
  return (
    resolutionScopeMatches(resolution, plan.businessId, plan.survivorLeadId, plan.loserLeadId) &&
    r.businessId === plan.businessId &&
    r.survivorLeadId === plan.survivorLeadId &&
    r.loserLeadId === plan.loserLeadId
  );
}
